name: Run tests

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello step
        run: echo "Hello world!"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 21.7.3
      - name: Install Dependencies
        run: npm install
      - name: Run tests
        run: npm test
